# Generated by Django 4.2 on 2025-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Draft', 'Draft')], default='Active', max_length=100),
        ),
    ]
